### PR TITLE
merging from picker: raise error if failed and apply merge defaults

### LINKED ISSUE #657: Merging PR from picker displays success message even if it failed
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

When merging not mergeable PR (checks haven't been completed or they have been unsuccessful, no review etc.) from picker (telescope in my case) I get `Merged PR 3502!` displayed nevertheless.

### Describe what you expected to happen

Even rough error message would have been better, like the one with `Octo pr merge`:

```
X Pull request .../...#3502 is not mergeable: the merge commit cannot be cleanly created.
```

### How to reproduce it (as minimally and precisely as possible)

1. Find PR which is not mergeable
2. Select it in `Octo pr search` for example (don't open)
3. Press "merge pr" binding (`<C-r>` by default)

### PR DESCRIPTION
**Pull request by macovsky**
### Describe what this PR does / why we need it

- raises error when merging from picker failed (like `Octo pr merge` does)
- adds `default_delete_branch` setting which can be overridden with
`delete`/`nodelete` argument to `Octo pr merge`
- also applies all merge defaults when merging from picker

### Does this pull request fix one issue?

Fixes #657

### Describe how to verify it

1. Find PR which is not mergeable
2. Select it in `Octo pr search` for example (don't open)
3. Press "merge pr" binding (`<C-r>` by default)
4. See error message

### Checklist

- [ ] Passing tests and linting standards
- [ ] Documentation updates in README.md and doc/octo.txt

### CODE REVIEW

File: lua/octo/utils.lua [hunk 1]
```diff
@@ -364,17 +364,41 @@ function M.checkout_pr_sync(pr_number)
...
+---Merges a PR by number
 function M.merge_pr(pr_number)
   if not Job then
+    M.error "Aborting PR merge"
     return
   end
+
+  local conf = config.values
+
+  local args = { "pr", "merge", pr_number, "--delete-branch" }
```
Comment (macovsky) [inline lua/octo/utils.lua:386]: since `--delete-branch` isn't added in `Octo pr merge` by default maybe we should add a setting for it and apply it by default in both cases?

Comment (pwntester) [reply lua/octo/utils.lua:386]: Agreed, please add a new setting and apply it consistently

File: lua/octo/commands.lua [hunk 2]
```diff
@@ -1117,43 +1117,32 @@ function M.pr_checks()
...
-    elseif defaultMergeMethod == "rebase" then
-      table.insert(args, "--rebase")
-    else
-      table.insert(args, "--merge")
+  utils.insert_merge_flag(args, merge_method)
+
+  local delete_branch = conf.default_delete_branch
+  for _, param in ipairs(params) do
+    if param == "delete" then
+      delete_branch = true
```
Comment (macovsky) [inline lua/octo/commands.lua:1141]: we can also add `nodelete` param to `Octo pr merge` to turn it off if `default_delete_branch=true`

File: lua/octo/utils.lua (hunk 1 above)
Comment (macovsky) [reply lua/octo/utils.lua]: added `default_delete_branch`

File: lua/octo/commands.lua (hunk 2 above)
Comment (macovsky) [reply lua/octo/commands.lua:1141]: added `nodelete` argument to `Octo pr merge`

**Review by pwntester — APPROVED** [review]

File: lua/octo/commands.lua (hunk 2 above)
Comment (pwntester) [reply lua/octo/commands.lua:1141]: Thanks!

**Review by pwntester — APPROVED** [review]
