### PR TITLE
fix: skip ProjectV2Events by config key default_to_projects_v2 (#1234)

### LINKED ISSUE #1234: Project Events not available on GitHub enterprise
@williambdean, this update broke my enterprise Github connection since these events don't exists(?).

It wasn't marked as a `Breaking Change`, not sure it should have?

```sh
gh: No such type AddedToProjectV2Event, so it can't be a fragment condition                                                                    
No such type RemovedFromProjectV2Event, so it can't be a fragment condition                                                                    
No such type ProjectV2ItemStatusChangedEvent, so it can't be a fragment condition 
```

Do you know if there could be a flag to swap this on or off?

_Originally posted by @phdah in https://github.com/pwntester/octo.nvim/issues/1184#issuecomment-3468874962_

### PR DESCRIPTION
**Pull request by f3nrir92**
### Describe what this PR does / why we need it

There are issues using Octo on GitHub Enterprice instances after merging pwntester/octo.nvim/pull/1215. Now configuration setting `default_to_projects_v2` also disables sending v2 events into Github API.

### Does this pull request fix one issue?

Fixes #1234 

### Checklist

- [x] Passing tests and linting standards
- [x] Documentation updates in README.md and doc/octo.txt

### CODE REVIEW

**Comment by williambdean** [comment]
Thanks for the PR @f3nrir92 !

I am getting this print out when opening nvim now...

```
Octo default_to_projects_v2 = true
fragment PullRequestTimelineItemsConnectionFragment on PullRequestTimelineItemsConnection {
  nodes {
      __typename
    ...AssignedEventFragment
    ...ClosedEventFragment
    ...ConnectedEventFragment
    ...ConvertToDraftEventFragment
    ...CrossReferencedEventFragment
    ...DemilestonedEventFragment
    ...IssueCommentFragment
    ...LabeledEventFragment
    ...MergedEventFragment
    ...MilestonedEventFragment
    ...PullRequestCommitFragment
    ...PullRequestReviewFragment
    ...ReadyForReviewEventFragment
    ...RenamedTitleEventFragment
    ...ReopenedEventFragment
    ...ReviewDismissedEventFragment
    ...ReviewRequestRemovedEventFragment
    ...ReviewRequestedEventFragment
    ...UnlabeledEventFragment
    ...DeployedEventFragment
    ...HeadRefDeletedEventFragment
    ...HeadRefRestoredEventFragment
    ...HeadRefForcePushedEventFragment
    ...AutoSquashEnabledEventFragment
    ...AddedToProjectV2EventFragment
    ...RemovedFromProjectV2EventFragment
    ...ProjectV2ItemStatusChangedEventFragment

  }
}
```

Maybe there needs to be a default value for the config?

EDIT: Found that there is a vim.notify. Let's remove those lines.

**Comment by f3nrir92** [comment]
@williambdean Sorry, my bad... just forgot to remove debug output 🤦

File: lua/octo/gh/fragments.lua [hunk 1]
```diff
@@ -1016,31 +1025,54 @@ fragment PullRequestTimelineItemsConnectionFragment on PullRequestTimelineItemsC
...
----@field milestone { title: string, state: string }
----@field author { login: string }
-
-M.issue_information = [[
+]],
+    pull_request_timeline_items_connection_fragments
+  )
+
+  vim.notify("Octo default_to_projects_v2 = " .. tostring(config.values.default_to_projects_v2))
+  vim.notify(M.pull_request_timeline_items_connection)
```
Comment (williambdean) [inline lua/octo/gh/fragments.lua:1056]: Let's remove these

**Comment by williambdean** [comment]
On another note (and not blocking this PR): Do you know if there is a way to detect if a repo is on GHE vs github.com? Maybe just from the remote URL? I'd think it'd be useful to allow for projects_v2 in github.com repos while disabling them for GHE repos.

**Comment by f3nrir92** [comment]
> Do you know if there is a way to detect if a repo is on GHE vs github.com? Maybe just from the remote URL?

You're right. I have no idea except checking the remote URL. And maybe there is some information in API, but quick search gave me nothing =(

**Review by williambdean — APPROVED** [review]
Thanks for the quick fix and PR! @f3nrir92
