### PR TITLE
fix: support finding pr branch via git config branch keys

### LINKED ISSUE #799: Could not start a review of GitHub PR
Recently, when I start a review in a Github PR I get this error

```
Error executing vim.schedule lua callback: ...rano/.local/share/nvim/lazy/octo.nvim/lua/octo/utils.lua:459: attempt to index a nil value
stack traceback:
        ...rano/.local/share/nvim/lazy/octo.nvim/lua/octo/utils.lua:459: in function 'in_pr_branch'
        ...ocal/share/nvim/lazy/octo.nvim/lua/octo/reviews/init.lua:177: in function 'initiate'
        ...ocal/share/nvim/lazy/octo.nvim/lua/octo/reviews/init.lua:99: in function 'callback'
        ...ocal/share/nvim/lazy/octo.nvim/lua/octo/reviews/init.lua:75: in function 'cb'
        ...no/.local/share/nvim/lazy/octo.nvim/lua/octo/gh/init.lua:163: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I cloned a specific, and clean, copy of the repo to be reviewed, so there is no ongoing work

Using
```
$ nvim --version
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189
```

Octo:
* branch master
* commit 9f7467d

This used to work flawlessly in the past

### PR DESCRIPTION
**Pull request by ldelossa**
Fixes #799

When the gh cli tool checks out a branch created from a fork of the origin it places remote tracking info directly in git config at a key derived from branch.{branch_name} prefix.

Octo did not consider this when checking if the repository is checked out to the branch pending merge into the origin.

Update the `in_pr_branch` function to also check if the current PR has a git configuration which provides details of the upstream fork branch.

See the following `man git-config` entries for more details:
```
       branch.<name>.remote
           When on branch <name>, it tells git fetch and git push which remote to fetch from/push to. The remote to push to may
           be overridden with remote.pushDefault (for all branches). The remote to push to, for the current branch, may be
           further overridden by branch.<name>.pushRemote. If no remote is configured, or if you are not on any branch and there
           is more than one remote defined in the repository, it defaults to origin for fetching and remote.pushDefault for
           pushing. Additionally, . (a period) is the current local repository (a dot-repository), see branch.<name>.merge's
           final note below.

       branch.<name>.pushRemote
           When on branch <name>, it overrides branch.<name>.remote for pushing. It also overrides remote.pushDefault for
           pushing from branch <name>. When you pull from one place (e.g. your upstream) and push to another place (e.g. your
           own publishing repository), you would want to set remote.pushDefault to specify the remote to push to for all
           branches, and use this option to override it for a specific branch.

       branch.<name>.merge
           Defines, together with branch.<name>.remote, the upstream branch for the given branch. It tells git fetch/git
           pull/git rebase which branch to merge and can also affect git push (see push.default). When in branch <name>, it
           tells git fetch the default refspec to be marked for merging in FETCH_HEAD. The value is handled like the remote part
           of a refspec, and must match a ref which is fetched from the remote given by "branch.<name>.remote". The merge
           information is used by git pull (which at first calls git fetch) to lookup the default branch for merging. Without
           this option, git pull defaults to merge the first refspec fetched. Specify multiple values to get an octopus merge.
           If you wish to setup git pull so that it merges into <name> from another branch in the local repository, you can
           point branch.<name>.merge to the desired branch, and use the relative path setting . (a period) for
           branch.<name>.remote.

```

### Checklist

- [x] Passing tests and linting standards
- [ ] Documentation updates in README.md and doc/octo.txt

### CODE REVIEW

**Comment by wd60622** [comment]
Will take a look tomorrow

File: lua/octo/utils.lua [hunk 1]
```diff
@@ -465,6 +470,62 @@ function M.in_pr_branch(pr)
...
+  -- use > 2 since there maybe some garbage white space at the end of the map.
+  if #merge_config_kv < 2 then
+    return false
+  end
+
+  local upstream_branch_ref = merge_config_kv[2]
+
+  -- remove the prefix /refs/heads/ from upstream_branch_ref resulting in
+  -- branch's name.
+  local upstream_branch_name = string.gsub(upstream_branch_ref, "^refs/heads/", "")
```
Comment (wd60622) [inline lua/octo/utils.lua:513]: I'd suggest pulling this out. It would simply the logic of function 

```lua
local function config_branch_name()
  -- The logic here
end

function M.in_pr_brand_config_tracker(pr)
  return upstream_branch_name:lower() == pr.head_ref_name
end

```

**Review by wd60622 — APPROVED** [review]
From my point of view, looks good. One suggestion for readibility

**Comment by ldelossa** [comment]
@wd60622 

I handled your feedback. Also rebased to latest HEAD, so the merge commit is gone here.

**Comment by clobrano** [comment]
It seems to fix the problem for me too
Thanks!

**Review by wd60622 — APPROVED** [review]
Thanks for adjustment and pr!
