### PR TITLE
fix: handle @ symbol in PR title parsing

### LINKED ISSUE #1439: Writing a PR buffer errors when the title contains @
### Describe what happened and what your expected to happen

I tried updating the description of a PR with a title that included an `@` (I'll use `@company/package: fix some thing` as an example) symbol and I got the following error:
```
error parsing "input[title]" value: open company/package: fix some thing: no such file or directory
```

I don't think there should be parsing running on the title field?

### How to reproduce it (as minimally and precisely as possible)

- Create a PR with the following title: `@company/package: fix some thing`
- View the PR with `Octo pr view`
- Write the buffer

### Tell us your environment

- nvim version: `v0.11.5`
- octo.nvim commit hash: `c14f5b6`
- GitHub CLI version (`gh --version`): `gh version 2.83.2 (nixpkgs)`
- OS: macOS Tahoe 26.3 (25D125)
- GitHub product (GitHub, GitHub Enterprise, GHEC / See guide to determine [here](https://docs.github.com/en/get-started/using-github-docs/about-versions-of-github-docs#determining-which-github-product-you-use)): GitHub

### Anything else we need to know?

I don't think so!

### PR DESCRIPTION
**Pull request by VedantMadane**
Fixes #1439

### CODE REVIEW

**Comment by williambdean** [comment]
Thanks for the PR! Can you run pre-commit?

File: lua/octo/model/octo-buffer.lua [hunk 1]
```diff
@@ -366,26 +366,30 @@ function OctoBuffer:do_save_title_and_body()
...
       jq = ".data.updateDiscussion.discussion"
-      input["discussionId"] = id
+      input_F["discussionId"] = id
     end
 
     gh.api.graphql {
       query = query,
-      F = { input = input },
+      f = { input = input_f },
+      F = { input = input_F },
```
Comment (williambdean) [inline lua/octo/model/octo-buffer.lua:394]: Should be fine!

File: lua/octo/model/octo-buffer.lua [hunk 2]
```diff
@@ -366,26 +366,30 @@ function OctoBuffer:do_save_title_and_body()
       return
     end
 
-    local input = { body = desc_metadata.body, title = title_metadata.body }
+    -- Use f (raw-field) for body and title to avoid gh CLI interpreting @ as file path
+    -- (see https://github.com/cli/cli/issues/5979 - -F interprets @, -f treats as literal)
+    local input_f = { body = desc_metadata.body, title = title_metadata.body }
+    local input_F = {}
```
Comment (williambdean) [inline lua/octo/model/octo-buffer.lua:374]: Will likely need the types here.

**Review by williambdean — APPROVED** [review]

**Comment by VedantMadane** [comment]
Added type annotations to input_f and input_F tables as suggested. Ready for merge.

**Comment by williambdean** [comment]
Still seeing some failing typing: https://github.com/pwntester/octo.nvim/actions/runs/23746259587

**Comment by VedantMadane** [comment]
@williambdean Rebased on master — the typing failure was in \writers.lua:324\ which isn't part of this PR. Looks like the \
o-unknown\ diagnostic was resolved in a recent master commit. CI should be green now.

**Comment by williambdean** [comment]
Thanks @VedantMadane !
